import fs from 'node:fs/promises';
import path from 'node:path';

/**
 * Layout of the writable DATA_DIR, where non-local sources are materialised:
 *
 *   <DATA_DIR>/projects/<projectId>/sources/<sourceId>/current/   files the indexer scans (upload, notion)
 *   <DATA_DIR>/projects/<projectId>/sources/<sourceId>/repo/      git checkout (scanned at repo/<subdir>)
 *   <DATA_DIR>/projects/<projectId>/sources/<sourceId>/.staging/  upload sessions (dot-dir: never scanned)
 *
 * Ids are UUIDs generated by the database, so they are safe path segments.
 */

const UUID_RE = /^[0-9a-f-]{36}$/i;

function assertId(id: string, what: string): void {
  if (!UUID_RE.test(id)) throw new Error(`Invalid ${what} id`);
}

export function projectDir(dataDir: string, projectId: string): string {
  assertId(projectId, 'project');
  return path.join(dataDir, 'projects', projectId);
}

export function sourceDir(dataDir: string, projectId: string, sourceId: string): string {
  assertId(sourceId, 'source');
  return path.join(projectDir(dataDir, projectId), 'sources', sourceId);
}

export function sourceCurrentDir(dataDir: string, projectId: string, sourceId: string): string {
  return path.join(sourceDir(dataDir, projectId, sourceId), 'current');
}

export function sourceRepoDir(dataDir: string, projectId: string, sourceId: string): string {
  return path.join(sourceDir(dataDir, projectId, sourceId), 'repo');
}

export function stagingDir(dataDir: string, projectId: string, sourceId: string, session: string): string {
  if (!/^[0-9a-f]{32}$/.test(session)) throw new Error('Invalid upload session id');
  return path.join(sourceDir(dataDir, projectId, sourceId), '.staging', session);
}

const RM_OPTS = { recursive: true, force: true, maxRetries: 5, retryDelay: 200 } as const;

export async function removeSourceDir(dataDir: string, projectId: string, sourceId: string): Promise<void> {
  await fs.rm(sourceDir(dataDir, projectId, sourceId), RM_OPTS);
}

export async function removeProjectDir(dataDir: string, projectId: string): Promise<void> {
  await fs.rm(projectDir(dataDir, projectId), RM_OPTS);
}

/** Atomically-ish replace `target` with `next` (rename swap; the old tree is removed afterwards). */
export async function swapDirectory(target: string, next: string): Promise<void> {
  const old = `${target}.old-${Date.now()}`;
  await fs.mkdir(path.dirname(target), { recursive: true });
  try {
    await fs.rename(target, old);
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code !== 'ENOENT') throw err;
  }
  await fs.rename(next, target);
  await fs.rm(old, RM_OPTS);
}

/** Copies every file of `from` into `to` (creating directories), overwriting existing files. */
export async function mergeDirectory(from: string, to: string): Promise<number> {
  let copied = 0;
  await fs.mkdir(to, { recursive: true });
  for (const entry of await fs.readdir(from, { withFileTypes: true })) {
    const src = path.join(from, entry.name);
    const dst = path.join(to, entry.name);
    if (entry.isDirectory()) copied += await mergeDirectory(src, dst);
    else if (entry.isFile()) {
      await fs.copyFile(src, dst);
      copied++;
    }
  }
  return copied;
}

/**
 * Removes project/source directories whose ids no longer exist in the database (a crash between
 * deleting the row and removing the directory leaves such orphans behind). Best effort; errors are ignored.
 */
export async function sweepOrphanDirs(dataDir: string, live: { projectIds: Set<string>; sourceIds: Set<string> }): Promise<string[]> {
  const removed: string[] = [];
  const projectsRoot = path.join(dataDir, 'projects');
  let projectEntries: string[];
  try {
    projectEntries = await fs.readdir(projectsRoot);
  } catch {
    return removed;
  }
  for (const pid of projectEntries) {
    if (!UUID_RE.test(pid)) continue;
    if (!live.projectIds.has(pid)) {
      await fs.rm(path.join(projectsRoot, pid), RM_OPTS).catch(() => undefined);
      removed.push(pid);
      continue;
    }
    const sourcesRoot = path.join(projectsRoot, pid, 'sources');
    let sourceEntries: string[] = [];
    try {
      sourceEntries = await fs.readdir(sourcesRoot);
    } catch {
      continue;
    }
    for (const sid of sourceEntries) {
      if (UUID_RE.test(sid) && !live.sourceIds.has(sid)) {
        await fs.rm(path.join(sourcesRoot, sid), RM_OPTS).catch(() => undefined);
        removed.push(`${pid}/${sid}`);
      }
    }
  }
  return removed;
}
