import { execFile } from 'node:child_process';
import { createCipheriv, createHash, createHmac, randomBytes } from 'node:crypto';
import { mkdtemp, rm } from 'node:fs/promises';
import { createServer, type Server } from 'node:http';
import type { AddressInfo } from 'node:net';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { promisify } from 'node:util';

import { eq } from 'drizzle-orm';
import type { PgTable } from 'drizzle-orm/pg-core';
import Fastify, { type FastifyInstance } from 'fastify';
import { afterAll, beforeAll, describe, expect, inject, it } from 'vitest';

import { remainingUnderOldKeys, reportLines, rotateSecrets, type RotationReport } from '../../scripts/rotate-secret.js';
import { webhookRoutes } from '../../src/admin/webhooks.js';
import { WEB_LIMIT_DEFAULTS } from '../../src/config.js';
import type { AppContext } from '../../src/context.js';
import type { Db } from '../../src/db/client.js';
import { documentSources, projects, type DocumentSourceRow } from '../../src/db/schema.js';
import {
  decryptSecret,
  decryptWebhookSecret,
  encryptSecret,
  keyringOf,
  secretKeyId,
  storedKeyId,
  type SecretKeyring,
} from '../../src/services/crypto.js';
import { ENCRYPTED_FIELDS, type EncryptedField } from '../../src/services/encrypted-fields.js';
import { openVerificationWindow } from '../../src/services/notion-webhook.js';
import { ConfluenceDriver } from '../../src/services/sources/confluence.js';
import type { DriverContext } from '../../src/services/sources/driver.js';
import { createSource } from '../../src/services/sources.js';
import { applySchema, createTestDatabase, dropTestDatabase, silentLogger, TEST_EMBEDDING_DIMENSIONS, type TestDatabase } from './support/postgres.js';

/**
 * A `SECRET_KEY` rotation on a running instance, from the first row written under the old key to the
 * day the old key is deleted ([ADR-0075](../../../.ssot/ADR.md#adr-0075)).
 *
 * **Every assertion here needs a database and most of them need a half-finished one**, which is the
 * reason this file exists beside the unit tests rather than inside them. Interrupting a pass, proving
 * that a row is readable at the moment the process died, and then proving the same pass finishes when
 * it is started again are statements about rows, not about functions.
 *
 * Two things reach outside this process and neither of them reaches a network:
 *
 * - A `node:http` server on the loopback interface answers the three Confluence REST endpoints the
 *   driver uses, and **refuses anything but the exact `Authorization` header** built from the stored
 *   token. That is deliberate: `ConfluenceDriver` takes an injected client in every other test, and an
 *   injected client is precisely the seam that skips `decryptSecret`. A rotation test that used it
 *   would prove nothing about whether the credential survived. Here the product's own path runs —
 *   read the column, open it with the ring, build the Basic header — and the server is the thing that
 *   says whether the token that came out is the token that went in.
 * - The command itself is run as a child process at the end, because criterion 5 is about what the
 *   command *prints*, and `reportLines` is only most of that.
 */

const baseUrl = inject('postgresBaseUrl');
const DIMS = TEST_EMBEDDING_DIMENSIONS;

/** Long enough for `SECRET_KEY`'s 32-character floor, and recognisable in any string that leaks one. */
const OLD_KEY = 'old-key-the-one-being-retired-oooooooooo';
const NEW_KEY = 'new-key-the-one-everything-moves-to-nnnn';
/** Never configured anywhere: the key a row nobody can open was written with. */
const LOST_KEY = 'lost-key-nobody-kept-a-copy-of-gggggggggg';

const EMAIL = 'ops@example.test';
const CONFLUENCE_TOKEN = 'atl-token-BUZZARD-the-credential-a-sync-needs';
const LEGACY_TOKEN = 'atl-token-PELICAN-sealed-in-a-v1-envelope';
const LEGACY_WEBHOOK = 'wh-KESTREL-written-in-the-clear-before-adr-0075';
const NOTION_TOKEN = 'secret_verification-OSPREY-minted-by-notion';
const LOST_TOKEN = 'atl-token-CONDOR-under-a-key-nobody-has';
/** The value a concurrent writer replaces mid-pass, and the one it replaces it with. */
const RACE_LOSER = 'atl-token-MERLIN-the-value-the-pass-had-read';
const RACE_WINNER = 'atl-token-HARRIER-written-while-the-pass-ran';

let database: TestDatabase;
let db: Db;
let dataDir: string;
let app: FastifyInstance;
let server: Server;
let confluenceBaseUrl: string;

let projectId: string;
let wikiId: string;
let repoId: string;
let legacyId: string;
let notionId: string;

/** Generated by `createSource`, so it is only knowable by opening the column the rotation rewrites. */
let gitWebhookSecret = '';
/** The exact `v1.` string that was in the database before anything rotated (criterion 2). */
let v1BeforeRotation = '';
/** The finished run's report, asserted about again in the "what the command says" block. */
let finishedReport: RotationReport;

const ring = (current: string, previous?: string): SecretKeyring => ({ current, previous });

/** A `v1.` envelope exactly as `crypto.ts` wrote them before this phase: no key identity anywhere in it. */
function v1(plain: string, secretKey: string): string {
  const iv = randomBytes(12);
  const cipher = createCipheriv('aes-256-gcm', createHash('sha256').update(secretKey, 'utf8').digest(), iv);
  const ct = Buffer.concat([cipher.update(plain, 'utf8'), cipher.final()]);
  return ['v1', iv.toString('base64url'), cipher.getAuthTag().toString('base64url'), ct.toString('base64url')].join('.');
}

/**
 * Every stored value in every column the registry names.
 *
 * Driven by `ENCRYPTED_FIELDS` rather than by two column names written out here, for the same reason
 * the command is: a column added later is swept by this file on the day it is added, and a column
 * dropped from the registry takes these assertions down with it.
 */
async function storedValues(): Promise<Array<{ field: EncryptedField; id: string; value: string }>> {
  const out: Array<{ field: EncryptedField; id: string; value: string }> = [];
  for (const field of ENCRYPTED_FIELDS) {
    const rows = (await db.select({ id: field.id, value: field.column }).from(field.table as PgTable)) as Array<{ id: string; value: string | null }>;
    for (const row of rows) if (row.value !== null) out.push({ field, id: row.id, value: row.value });
  }
  return out;
}

/** Opens a value the way the product opens it: the webhook column tolerates a legacy plaintext, the other does not. */
function open(entry: { field: EncryptedField; value: string }, keys: SecretKeyring): string {
  return entry.field.legacyPlaintext ? decryptWebhookSecret(entry.value, keys) : decryptSecret(entry.value, keys);
}

async function sourceRow(id: string): Promise<DocumentSourceRow> {
  const [row] = await db.select().from(documentSources).where(eq(documentSources.id, id));
  return row;
}

/** Nothing a rotation touches may appear in anything a rotation prints. */
function expectNoPlaintext(text: string): void {
  for (const secret of [
    CONFLUENCE_TOKEN,
    LEGACY_TOKEN,
    LEGACY_WEBHOOK,
    NOTION_TOKEN,
    LOST_TOKEN,
    RACE_LOSER,
    RACE_WINNER,
    gitWebhookSecret,
    OLD_KEY,
    NEW_KEY,
    LOST_KEY,
  ]) {
    if (secret) expect(text).not.toContain(secret);
  }
}

// ---------------------------------------------------------------------------------------------
// The Confluence site, on the loopback interface.
// ---------------------------------------------------------------------------------------------

interface StubPage {
  id: string;
  title: string;
  version: number;
  body: string;
}

const PAGES: StubPage[] = [
  { id: '4411', title: 'Rotation runbook', version: 3, body: '<p>Set SECRET_KEY_PREVIOUS, then the new key.</p>' },
  { id: '4412', title: 'Where the key lives', version: 1, body: '<p>In the environment, and in the operator&#39;s password manager.</p>' },
];

const expectedAuthorization = `Basic ${Buffer.from(`${EMAIL}:${CONFLUENCE_TOKEN}`, 'utf8').toString('base64')}`;
let authorized = 0;
let refused = 0;

function startConfluence(): Promise<Server> {
  const listener = createServer((req, res) => {
    const url = new URL(req.url ?? '/', 'http://127.0.0.1');
    const json = (status: number, body: unknown): void => {
      res.writeHead(status, { 'content-type': 'application/json' });
      res.end(JSON.stringify(body));
    };

    // The whole point of this server: the token that came out of the database is the only thing that
    // opens it, so a sync that succeeds is a credential that survived the rotation.
    if (req.headers.authorization !== expectedAuthorization) {
      refused += 1;
      return json(401, { message: 'Unauthorized' });
    }
    authorized += 1;

    if (url.pathname === '/wiki/rest/api/user/current') return json(200, { displayName: 'Rotation Robot' });
    if (url.pathname === '/wiki/rest/api/search') {
      const limit = Number(url.searchParams.get('limit') ?? '50');
      const results = PAGES.slice(0, limit).map((page) => ({
        lastModified: '2026-09-20T10:00:00.000Z',
        content: {
          id: page.id,
          title: page.title,
          space: { key: 'DOCS' },
          version: { number: page.version },
          ancestors: [],
          _links: { webui: `/spaces/DOCS/pages/${page.id}` },
        },
      }));
      return json(200, { results, totalSize: PAGES.length });
    }
    const page = /^\/wiki\/rest\/api\/content\/(\d+)$/.exec(url.pathname);
    if (page) {
      const found = PAGES.find((candidate) => candidate.id === page[1]);
      if (found) return json(200, { body: { storage: { value: found.body } } });
    }
    return json(404, { message: 'not found' });
  });
  return new Promise((resolve) => listener.listen(0, '127.0.0.1', () => resolve(listener)));
}

function driverContext(keys: SecretKeyring): DriverContext {
  return {
    db,
    log: silentLogger,
    config: {
      ...WEB_LIMIT_DEFAULTS,
      ALLOWED_DOC_ROOTS: [dataDir],
      DATA_DIR: path.join(dataDir, 'data'),
      SECRET_KEY: keys.current,
      SECRET_KEY_PREVIOUS: keys.previous,
      IGNORE_GLOBS: [],
    } as DriverContext['config'],
  };
}

beforeAll(async () => {
  database = await createTestDatabase(baseUrl, 'secret_rotation');
  await applySchema(database, DIMS);
  db = database.db;

  dataDir = await mkdtemp(path.join(tmpdir(), 'secret-rotation-'));
  server = await startConfluence();
  confluenceBaseUrl = `http://127.0.0.1:${(server.address() as AddressInfo).port}/wiki`;

  const [project] = await db.insert(projects).values({ name: 'rotation' }).returning({ id: projects.id });
  projectId = project.id;

  const opts = { allowedRoots: [dataDir], keys: ring(OLD_KEY) };

  // Written by the product, under the key that is about to be retired.
  const wiki = await createSource(
    db,
    projectId,
    {
      type: 'confluence',
      name: 'wiki',
      secret: CONFLUENCE_TOKEN,
      config: { baseUrl: confluenceBaseUrl, email: EMAIL, spaceKeys: ['DOCS'], extensions: ['md'] },
    },
    opts,
  );
  wikiId = wiki.id;

  // A git source mints its own webhook secret, so the only way to learn it is to open the column.
  const repo = await createSource(db, projectId, { type: 'git', name: 'repo', config: { url: 'https://git.example.test/acme/docs.git' } }, opts);
  repoId = repo.id;
  gitWebhookSecret = decryptWebhookSecret(repo.webhookSecret ?? '', ring(OLD_KEY));
  expect(gitWebhookSecret).toHaveLength(64);

  // The instance as it was before this phase shipped: a `v1.` envelope with no key identity, and a
  // webhook secret sitting in the clear. Both are inserted directly, because no code path writes
  // either of these shapes any more — which is exactly why an upgrade has to be tested from the row.
  v1BeforeRotation = v1(LEGACY_TOKEN, OLD_KEY);
  const [legacy] = await db
    .insert(documentSources)
    .values({
      projectId,
      type: 'git',
      name: 'legacy',
      config: { url: 'https://git.example.test/acme/legacy.git', branch: 'main', extensions: ['md'] },
      secretEnc: v1BeforeRotation,
      webhookSecret: LEGACY_WEBHOOK,
    })
    .returning({ id: documentSources.id });
  legacyId = legacy.id;

  const [notion] = await db
    .insert(documentSources)
    .values({ projectId, type: 'notion', name: 'workspace', config: { rootIds: [], extensions: ['md'] } })
    .returning({ id: documentSources.id });
  notionId = notion.id;
}, 180_000);

afterAll(async () => {
  await app?.close();
  await new Promise<void>((resolve) => server?.close(() => resolve()));
  await rm(dataDir, { recursive: true, force: true });
  await dropTestDatabase(baseUrl, database);
});

describe('before the pass runs', () => {
  it('holds four values, none of them under the new key, all of them readable with the ring', async () => {
    const values = await storedValues();
    expect(values).toHaveLength(4);
    for (const entry of values) {
      expect(storedKeyId(entry.value)).not.toBe(secretKeyId(NEW_KEY));
      expect(open(entry, ring(NEW_KEY, OLD_KEY))).toBeTruthy();
    }
    // Two shapes the new key alone cannot answer for, and one it does not need to: the plaintext.
    expect(storedKeyId(v1BeforeRotation)).toBeNull();
    expect(await remainingUnderOldKeys(db, ring(NEW_KEY, OLD_KEY))).toBe(4);
  });
});

describe('a pass that is interrupted half way', () => {
  it('leaves every row readable and the rest of the work still to do', async () => {
    // Two writes, and then the process dies — the shape of an operator's Ctrl-C, an OOM kill, or a
    // deploy that restarted the container mid-run.
    await expect(
      rotateSecrets(db, ring(NEW_KEY, OLD_KEY), {
        beforeWrite: (_field, written) => {
          if (written >= 2) throw new Error('interrupted');
        },
      }),
    ).rejects.toThrow('interrupted');

    const values = await storedValues();
    expect(values).toHaveLength(4);

    // **The property the phase is really about.** Not "half the rows were converted" — that is only
    // arithmetic — but that at the moment the process stopped, no row had become unreadable.
    for (const entry of values) {
      expect(() => open(entry, ring(NEW_KEY, OLD_KEY))).not.toThrow();
    }

    const converted = values.filter((entry) => storedKeyId(entry.value) === secretKeyId(NEW_KEY));
    expect(converted).toHaveLength(2);
    expect(await remainingUnderOldKeys(db, ring(NEW_KEY, OLD_KEY))).toBe(2);
  });

  it('finishes when it is started again, and the second run converts only what is left', async () => {
    finishedReport = await rotateSecrets(db, ring(NEW_KEY, OLD_KEY));

    expect(finishedReport.keyId).toBe(secretKeyId(NEW_KEY));
    expect(finishedReport.previousKeyId).toBe(secretKeyId(OLD_KEY));
    expect(finishedReport.remaining).toBe(0);

    const byField = new Map(finishedReport.fields.map((outcome) => [outcome.field, outcome]));
    // Both columns the registry names were walked; neither is named here as a string the registry
    // does not also produce.
    expect([...byField.keys()].sort()).toEqual([...ENCRYPTED_FIELDS].map((field) => field.name).sort());

    const secrets = byField.get('document_sources.secret_enc');
    if (!secrets) throw new Error('the registry no longer carries document_sources.secret_enc');
    expect(secrets).toMatchObject({ scanned: 2, alreadyCurrent: 2, reEncrypted: 0, sealed: 0, raced: 0, unreadable: [] });

    const webhooks = byField.get('document_sources.webhook_secret');
    if (!webhooks) throw new Error('the registry no longer carries document_sources.webhook_secret');
    // One re-encrypted (the generated one), one *sealed* — the value that had never been encrypted.
    expect(webhooks).toMatchObject({ scanned: 2, alreadyCurrent: 0, reEncrypted: 1, sealed: 1, raced: 0, unreadable: [] });

    for (const entry of await storedValues()) {
      expect(storedKeyId(entry.value)).toBe(secretKeyId(NEW_KEY));
    }
  });

  it('does nothing at all the third time', async () => {
    const report = await rotateSecrets(db, ring(NEW_KEY, OLD_KEY));
    expect(report.remaining).toBe(0);
    for (const outcome of report.fields) {
      expect(outcome.reEncrypted + outcome.sealed + outcome.raced).toBe(0);
      expect(outcome.alreadyCurrent).toBe(outcome.scanned);
    }
  });
});

describe('a value written before the rotation', () => {
  it('opens under the new key, and holds exactly what the v1 envelope held', async () => {
    const legacy = await sourceRow(legacyId);

    // The row is a `v2.` envelope now, and the string it replaced is not.
    expect(legacy.secretEnc).not.toBe(v1BeforeRotation);
    expect(storedKeyId(v1BeforeRotation)).toBeNull();
    expect(storedKeyId(legacy.secretEnc ?? '')).toBe(secretKeyId(NEW_KEY));

    // With the previous key gone from the environment — the last step of the runbook.
    expect(decryptSecret(legacy.secretEnc ?? '', ring(NEW_KEY))).toBe(LEGACY_TOKEN);
    expect(decryptWebhookSecret(legacy.webhookSecret ?? '', ring(NEW_KEY))).toBe(LEGACY_WEBHOOK);

    // And a `v1.` value that some other process wrote *during* the rotation is still readable, which
    // is what makes the pass a catch-up rather than a cutover.
    expect(decryptSecret(v1BeforeRotation, ring(NEW_KEY, OLD_KEY))).toBe(LEGACY_TOKEN);
  });
});

describe('a row somebody else writes while the pass is reading it', () => {
  let racerId = '';

  beforeAll(async () => {
    const [racer] = await db
      .insert(documentSources)
      .values({
        projectId,
        type: 'confluence',
        name: 'racer',
        config: { baseUrl: confluenceBaseUrl, email: EMAIL, spaceKeys: ['DOCS'], extensions: ['md'] },
        secretEnc: encryptSecret(RACE_LOSER, ring(OLD_KEY)),
      })
      .returning({ id: documentSources.id });
    racerId = racer.id;
  });

  afterAll(async () => {
    await db.delete(documentSources).where(eq(documentSources.id, racerId));
  });

  /**
   * The claim the row-at-a-time write is *for*, measured rather than asserted in a comment: a pass
   * that is slower than the operator editing a source must not put the value it read back over the
   * top of the value that operator saved.
   *
   * Every other row is already under the current key by the time this block runs, so this row is the
   * pass's only write and `beforeWrite` fires exactly once — inside the window between the read and
   * the `UPDATE`, which is the only place the race can happen.
   */
  it('counts the row as raced and leaves the other writer\u2019s value in place', async () => {
    let interference = 0;
    const report = await rotateSecrets(db, ring(NEW_KEY, OLD_KEY), {
      beforeWrite: async (field) => {
        if (field.name !== 'document_sources.secret_enc' || interference > 0) return;
        interference += 1;
        // What the admin API does when somebody pastes a new token: writes it with the current key,
        // knowing nothing about the pass that is running.
        await db
          .update(documentSources)
          .set({ secretEnc: encryptSecret(RACE_WINNER, ring(NEW_KEY)) })
          .where(eq(documentSources.id, racerId));
      },
    });
    expect(interference).toBe(1);

    const secrets = report.fields.find((outcome) => outcome.field === 'document_sources.secret_enc');
    // Read, overtaken, and counted as overtaken — not re-encrypted, not an error.
    expect(secrets).toMatchObject({ raced: 1, reEncrypted: 0, sealed: 0, unreadable: [] });

    // **The guarantee itself.** The concurrent write is what the row holds afterwards.
    const row = await sourceRow(racerId);
    expect(decryptSecret(row.secretEnc ?? '', ring(NEW_KEY))).toBe(RACE_WINNER);
    // And the pass still finished: a raced row is under the current key, because whoever won the
    // race wrote with it.
    expect(report.remaining).toBe(0);
  });
});

describe('once SECRET_KEY_PREVIOUS is removed', () => {
  beforeAll(async () => {
    app = Fastify({ logger: false });
    const ctx = {
      db,
      // No `SECRET_KEY_PREVIOUS`: this instance has forgotten the old key entirely.
      config: { SECRET_KEY: NEW_KEY, WEBHOOK_MIN_INTERVAL_MINUTES: 5 },
      indexer: { isBusy: () => false, enqueue: () => ({ phase: 'queued', queuedAt: new Date().toISOString() }) },
      log: silentLogger,
    } as unknown as AppContext;
    await app.register(webhookRoutes, { ctx });
    await app.ready();
  });

  it('still syncs the source whose credential the retired key encrypted', async () => {
    const before = authorized;
    const driver = new ConfluenceDriver(await sourceRow(wikiId), driverContext(ring(NEW_KEY)));

    const result = await driver.sync();

    // The site answered, which it only does for the exact Basic header built from the stored token.
    expect(refused).toBe(0);
    expect(authorized).toBeGreaterThan(before);
    expect(result.note ?? '').toContain('2');
    expect(result.configPatch?.syncProbeToken).toBeTruthy();
  });

  it('still verifies a webhook delivery signed with the secret the retired key encrypted', async () => {
    const payload = JSON.stringify({ ref: 'refs/heads/main' });
    const post = (sourceId: string, secret: string) =>
      app.inject({
        method: 'POST',
        url: `/api/webhooks/git/${sourceId}`,
        payload,
        headers: {
          'content-type': 'application/json',
          'x-github-event': 'push',
          'x-hub-signature-256': `sha256=${createHmac('sha256', secret).update(Buffer.from(payload)).digest('hex')}`,
        },
      });

    expect((await post(repoId, gitWebhookSecret)).statusCode).toBe(202);
    // The one that was plaintext until the pass sealed it verifies against the same string it always did.
    expect((await post(legacyId, LEGACY_WEBHOOK)).statusCode).toBe(202);
    // And a signature made with anything else is still refused, so the two above are not passing by accident.
    expect((await post(repoId, LEGACY_WEBHOOK)).statusCode).toBe(401);
  });

  it('encrypts the next secret it is given with the key that is now current', async () => {
    await openVerificationWindow(db, notionId);
    const res = await app.inject({
      method: 'POST',
      url: `/api/webhooks/notion/${notionId}`,
      payload: JSON.stringify({ verification_token: NOTION_TOKEN }),
      headers: { 'content-type': 'application/json' },
    });
    expect(res.statusCode).toBe(200);

    const row = await sourceRow(notionId);
    expect(row.webhookSecret).not.toBe(NOTION_TOKEN);
    expect(storedKeyId(row.webhookSecret ?? '')).toBe(secretKeyId(NEW_KEY));
    expect(decryptWebhookSecret(row.webhookSecret ?? '', ring(NEW_KEY))).toBe(NOTION_TOKEN);
  });
});

describe('what the command says out loud', () => {
  it('prints counts, column names and ids — and no secret of any kind', () => {
    const text = reportLines(finishedReport).join('\n');
    expectNoPlaintext(text);
    expect(text).toContain('document_sources.secret_enc');
    expect(text).toContain('document_sources.webhook_secret');
    expect(text).toContain('Nothing is left under an older key.');
    expect(text).toContain('Remove SECRET_KEY_PREVIOUS');
  });

  it('names a row no key can open by its id, leaves the value alone, and converts the rest anyway', async () => {
    const orphanValue = encryptSecret(LOST_TOKEN, ring(LOST_KEY));
    const [orphan] = await db
      .insert(documentSources)
      .values({
        projectId,
        type: 'git',
        name: 'orphan',
        config: { url: 'https://git.example.test/acme/orphan.git', branch: 'main', extensions: ['md'] },
        secretEnc: orphanValue,
        webhookSecret: 'wh-GANNET-a-neighbour-that-must-still-be-converted',
      })
      .returning({ id: documentSources.id });

    const report = await rotateSecrets(db, ring(NEW_KEY));
    const secrets = report.fields.find((outcome) => outcome.field === 'document_sources.secret_enc');
    expect(secrets?.unreadable).toEqual([orphan.id]);
    expect(report.remaining).toBe(1);

    // The neighbour in the same pass was still converted: one unreadable row is not a failed run.
    const row = await sourceRow(orphan.id);
    expect(storedKeyId(row.webhookSecret ?? '')).toBe(secretKeyId(NEW_KEY));
    // And the value that would not open was not overwritten — it is the only copy of whatever it holds.
    expect(row.secretEnc).toBe(orphanValue);

    const text = reportLines(report).join('\n');
    expectNoPlaintext(text);
    expect(text).toContain(orphan.id);
    expect(text).not.toContain(orphanValue);
    expect(text).toContain('1 value(s) are still not under the current key');

    await db.delete(documentSources).where(eq(documentSources.id, orphan.id));
  });

  it('prints no secret when it is run as the command an operator actually types', async () => {
    // Back under the old key, so the child process has something real to convert rather than a table
    // it can skip: this is the command, its configuration and its output, end to end.
    await db
      .update(documentSources)
      .set({ secretEnc: encryptSecret(CONFLUENCE_TOKEN, ring(OLD_KEY)) })
      .where(eq(documentSources.id, wikiId));

    const root = fileURLToPath(new URL('../../', import.meta.url));
    const { stdout, stderr } = await promisify(execFile)(path.join(root, 'node_modules', '.bin', 'tsx'), ['scripts/rotate-secret.ts'], {
      cwd: root,
      env: { ...process.env, DATABASE_URL: database.url, SECRET_KEY: NEW_KEY, SECRET_KEY_PREVIOUS: OLD_KEY },
    });

    expectNoPlaintext(stdout);
    expectNoPlaintext(stderr);
    expect(stdout).toContain('Nothing is left under an older key.');
    expect(storedKeyId((await sourceRow(wikiId)).secretEnc ?? '')).toBe(secretKeyId(NEW_KEY));
    expect(decryptSecret((await sourceRow(wikiId)).secretEnc ?? '', keyringOf({ SECRET_KEY: NEW_KEY }))).toBe(CONFLUENCE_TOKEN);
  }, 120_000);
});
